platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.3'
inputs:
  - name: super-stacker
outputs:
  - name: artifact
run:
  path: bash
  args:
    - -c
    - |
      set -e
      set -x
      cd super-stacker
      bundle
      rake spec
      rake package
      mv superstacker-*.gem ../artifact/
