platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.3'
inputs:
  - name: repo
run:
  path: bash
  args:
    - -c
    - |
      set -e
      set -x
      cd repo
      bundle
      rake spec
